services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    platform: linux/arm64
    image: ghcr.io/luka-lta/luka-lta-api/api-nginx:production

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: production
    platform: linux/arm64
    image: ghcr.io/luka-lta/luka-lta-api/api-php-fpm:production