name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image for nginx
        run: |
          docker compose -f docker-compose.development.yml build nginx
          docker tag lukalta/api-nginx:dev ghcr.io/${{ github.repository_owner }}/api-nginx:dev

      - name: Build Docker image for php-fpm
        run: |
          docker compose -f docker-compose.development.yml build php-fpm
          docker tag lukalta/api-php-fpm:dev ghcr.io/${{ github.repository_owner }}/api-php-fpm:dev

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/api-nginx:dev
          docker push ghcr.io/${{ github.repository_owner }}/api-php-fpm:dev